Feat overview of global db services
actiontech/sqle pull request #2480
Opened 2024-07-11 08:23 UTC by BugsGuru

## 关联的 issue
https://github.com/actiontech/dms-ee/issues/312

## 描述你的变更
添加接口：通过实例ID获取实例上未完成的工单数量

## 确认项（pr提交后操作）
> [!TIP]
> 请在指定**复审人**之前，确认并完成以下事项，完成后✅
----------------------------------------------------------------------
- [x] 我已完成自测
- [x] 我已在关联的issue里补充了实现方案
- [x] 我已在关联的issue里补充了测试影响面
- [x] 我已确认了变更的兼容性，如果不兼容则在issue里标记 `not_compatible`
- [x] 我已确认了是否要更新文档，如果要更新则在issue里标记 `need_update_doc`
----------------------------------------------------------------------

2024-07-11 11:37 UTC, ColdWaterLW requested changes

2024-07-11 11:37 UTC, ColdWaterLW commented on sqle/api/controller/v1/workflow.go
> +	if user.Name != model.DefaultAdminUser && user.Name != model.DefaultSysUser {
model.DefaultSysUser是啥

2024-07-11 11:37 UTC, ColdWaterLW commented on sqle/api/controller/v1/workflow.go
> +		// dms-todo: 判断是否是超级管理员/系统用户
todo是遗留了什么问题

2024-07-11 11:37 UTC, ColdWaterLW commented on sqle/api/controller/v1/workflow.go
> +// @router /v1/workflows_info_of_instances [get]
url注释和router不一样

2024-07-11 11:37 UTC, ColdWaterLW commented on sqle/api/app.go
> +		v1Router.GET("/unfinished_workflows_count", v1.GetUnfinishedWorkflowsCountOfInstances)
statistic_by_instance，这个名字后续要是有新增的统计项也可以用，把结构体名字也跟着改改吧

2024-07-12 02:11 UTC, BugsGuru commented on sqle/api/controller/v1/workflow.go
> +	if user.Name != model.DefaultAdminUser && user.Name != model.DefaultSysUser {
内置用户有admin和sys，dms调用的话token里的用户是sys，DefaultSysUser 是模仿DefaultAdminUser 在model里定义的常量“sys”

2024-07-12 09:01 UTC, ColdWaterLW approved these changes

2024-07-12 09:01 UTC, merged