Report push job
actiontech/sqle pull request #2541
Opened 2024-08-14 09:33 UTC by LordofAvernus

## 关联的 issue
https://github.com/actiontech/sqle/issues/2527
## 描述你的变更
- 推送配置定时更新推送任务
## 确认项（pr提交后操作）
> [!TIP]
> 请在指定**复审人**之前，确认并完成以下事项，完成后✅
----------------------------------------------------------------------
- [ ] 我已完成自测
- [ ] 我已在关联的issue里补充了实现方案
- [ ] 我已在关联的issue里补充了测试影响面
- [ ] 我已确认了变更的兼容性，如果不兼容则在issue里标记 `not_compatible`
- [ ] 我已确认了是否要更新文档，如果要更新则在issue里标记 `need_update_doc`
----------------------------------------------------------------------

2024-08-15 03:26 UTC, ColdWaterLW requested changes

2024-08-15 08:10 UTC, LordofAvernus commented on sqle/server/report_push_ce.go
> +func newPushJob(p *model.ReportPushConfig) (PushJob, error) {
社区版不支持

2024-08-16 02:49 UTC, ColdWaterLW requested changes

2024-08-16 02:49 UTC, ColdWaterLW commented on sqle/model/report_push_config.go
> +func (s Storage) GetLastUpdateReportPushConfig(lastSyncTime time.Time) ([]*ReportPushConfig, error) {
updated

2024-08-16 02:54 UTC, ColdWaterLW commented on sqle/model/report_push_config.go
> +func (s Storage) GetLastUpdateReportPushConfig(lastSyncTime time.Time) ([]*ReportPushConfig, error) {
名称 -> GetUpdatedReportPushConfigByTime ?

2024-08-16 03:44 UTC, ColdWaterLW requested changes

2024-08-16 03:44 UTC, ColdWaterLW commented on sqle/api/controller/v1/audit_plan.go
> +	BooleanOperator BooleanOperator     `json:"boolean_operator"`
Relational operator

2024-08-16 05:59 UTC, ColdWaterLW submitted a review, later dismissed

2024-08-16 05:59 UTC, ColdWaterLW commented on sqle/api/controller/v1/audit_plan.go
> +	if meta.HighPriorityParams != nil && len(meta.HighPriorityParams) > 0 {
后面那个条件可以覆盖前面这个条件吗

2024-08-16 05:59 UTC, ColdWaterLW commented on sqle/api/controller/v1/instance_audit_plan.go
> +	MarkHighPrioritySQL    bool                       `json:"mark_high_priority_sql"`
不是一个bool变量的名字

2024-08-16 05:59 UTC, ColdWaterLW commented on sqle/api/controller/v1/instance_audit_plan.go
> +	BooleanOperator string `json:"boolean_operator" form:"boolean_operator" default:">" enums:">,=,<" valid:"oneof=> = <"`
重命名

2024-08-16 05:59 UTC, ColdWaterLW commented on sqle/pkg/params/params.go
> +func (r *ParamsWithOperator) CompareParamValue(key string, inputValue string) (bool, error) {
这是一个比较完整的业务功能了，compare只是手段，其中的目的是判断sql是否是高优先级sql，建议根据业务改名。像compareInt()就不用改，因为逻辑属于比较通用的，非业务的，命名就只要说干了什么就好了

2024-08-16 05:59 UTC, ColdWaterLW commented on sqle/server/auditplan/job_task_handler.go
> +			if highPriorityCondition.Key == "audit_level" {
这些字符串用常量

2024-08-16 05:59 UTC, ColdWaterLW commented on sqle/server/auditplan/job_task_handler.go
> +func CheckSQLPriority(sqlList []*model.SQLManageRecord) ([]*model.SQLManageRecord, error) {
这里面修改了入参，建议把check改成update或set

2024-08-16 05:59 UTC, ColdWaterLW commented on sqle/server/auditplan/job_task_handler.go
> +					String: "high",
常量

2024-08-16 05:59 UTC, ColdWaterLW commented on sqle/pkg/params/params.go
> +func (r *ParamsWithOperator) CompareParamValue(key string, inputValue string) (bool, error) {
这些为啥都放在社区版

2024-08-16 07:04 UTC, LordofAvernus commented on sqle/api/controller/v1/instance_audit_plan.go
> +	MarkHighPrioritySQL    bool                       `json:"mark_high_priority_sql"`
IsMarkHighPrioritySQL

2024-08-16 07:09 UTC, LordofAvernus commented on sqle/api/controller/v1/instance_audit_plan.go
> +	BooleanOperator string `json:"boolean_operator" form:"boolean_operator" default:">" enums:">,=,<" valid:"oneof=> = <"`
RelationalOperator

2024-08-16 07:10 UTC, LordofAvernus commented on sqle/api/controller/v1/audit_plan.go
> +	if meta.HighPriorityParams != nil && len(meta.HighPriorityParams) > 0 {
保留吧，避免忘记赋值导致空指针

2024-08-16 07:19 UTC, LordofAvernus commented on sqle/api/controller/v1/instance_audit_plan.go
> +	MarkHighPrioritySQL    bool                       `json:"mark_high_priority_sql"`
NeedMarkHighPrioritySQL

2024-08-16 07:21 UTC, LordofAvernus commented on sqle/server/auditplan/job_task_handler.go
> +func CheckSQLPriority(sqlList []*model.SQLManageRecord) ([]*model.SQLManageRecord, error) {
SetSQLPriority

2024-08-16 07:34 UTC, LordofAvernus commented on sqle/server/auditplan/job_task_handler.go
> +			if highPriorityCondition.Key == "audit_level" {
const AuditLevel = "audit_level"

2024-08-16 08:11 UTC, sjjian commented on sqle/server/auditplan/job_task_handler.go
> +			var cpmpareParamVale string
`cpmpare`?

2024-08-16 09:02 UTC, LordofAvernus commented on sqle/api/controller/v1/audit_plan.go
> +	BooleanOperator BooleanOperator     `json:"boolean_operator"`
最终用operator

2024-08-16 09:14 UTC, sjjian approved these changes

2024-08-16 09:21 UTC, merged