Sql version manage
actiontech/sqle pull request #2612
Opened 2024-09-14 09:48 UTC by iwanghc

## 关联的 issue
https://github.com/actiontech/sqle-ee/issues/1807
## 描述你的变更
数据库版本管理场景一需求接口定义、模型定义、工单接口定义调整
## 确认项（pr提交后操作）
> [!TIP]
> 请在指定**复审人**之前，确认并完成以下事项，完成后✅
----------------------------------------------------------------------
- [ ] 我已完成自测
- [ ] 我已在关联的issue里补充了实现方案
- [ ] 我已在关联的issue里补充了测试影响面
- [ ] 我已确认了变更的兼容性，如果不兼容则在issue里标记 `not_compatible`
- [ ] 我已确认了是否要更新文档，如果要更新则在issue里标记 `need_update_doc`
----------------------------------------------------------------------

2024-09-18 08:00 UTC, ColdWaterLW requested changes

2024-09-18 08:04 UTC, ColdWaterLW commented on sqle/api/controller/v1/sql_version.go
> +// @router /v1/projects/{project_name}/sql_version/workflow/{workflow_id}/ [post]
不需要workflow层级

2024-09-20 06:32 UTC, winfredLIN commented on sqle/model/sql_version.go
> +	ProjectId     ProjectUID `gorm:"index; not null"`
这里能否改为一致的名称projectUID

2024-09-20 06:56 UTC, iwanghc commented on sqle/model/sql_version.go
> +	ProjectId     ProjectUID `gorm:"index; not null"`
sqle的model中，存储项目id的字段都叫project_id

2024-09-20 07:57 UTC, ColdWaterLW approved these changes

2024-09-20 07:57 UTC, merged