fix: panic when instance is deleted
actiontech/sqle pull request #2688
Opened 2024-10-16 08:14 UTC by littleniannian

## 关联的 issue
https://github.com/actiontech/sqle/issues/2479
## 描述你的变更
对于`dms.GetInstancesById`的返回值需要对exist进行校验后，再调用instance. 保证不出现panic。
## 确认项（pr提交后操作）
> [!TIP]
> 请在指定**复审人**之前，确认并完成以下事项，完成后✅
----------------------------------------------------------------------
- [ ] 我已完成自测
- [ ] 我已在关联的issue里补充了实现方案
- [ ] 我已在关联的issue里补充了测试影响面
- [ ] 我已确认了变更的兼容性，如果不兼容则在issue里标记 `not_compatible`
- [ ] 我已确认了是否要更新文档，如果要更新则在issue里标记 `need_update_doc`
----------------------------------------------------------------------

2024-10-16 08:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/actiontech/sqle?pullRequest=2688) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/actiontech/sqle?pullRequest=2688) before we can accept your contribution.<br/><hr/>**yuanjiawei** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/actiontech/sqle?pullRequest=2688) it.</sub>

2024-10-23 10:08 UTC, ColdWaterLW requested changes

2024-10-23 10:08 UTC, ColdWaterLW commented on sqle/server/pipeline/pipeline.go
> +		if !exist {
创建流水线如果没有选数据源会怎么样

2024-10-23 10:25 UTC, littleniannian commented on sqle/server/pipeline/pipeline.go
> +		if !exist {
不选数据源，`node.InstanceId`为0，不会走查询数据源的逻辑

2024-10-23 10:29 UTC, ColdWaterLW commented on sqle/server/pipeline/pipeline.go
> +		if !exist {
这个报错会在什么地方体现出来？是否方便排查

2024-10-24 01:46 UTC, littleniannian commented on sqle/server/pipeline/pipeline.go
> +		if !exist {
![image](https://github.com/user-attachments/assets/a1881177-6817-4ba0-8d5f-16b66081356a)

2024-10-24 01:46 UTC, littleniannian commented on sqle/server/pipeline/pipeline.go
> +		if !exist {
流水线详情页面，展示如上。

2024-10-25 02:12 UTC, sjjian commented on sqle/server/auditplan/task_type_mysql_schema_meta.go
> +		return nil, fmt.Errorf("instance: %v is not exist", ap.InstanceID)
如果错误内容都一样就抽取出来，另外可以检查一下是否有已经定义过的变量"instance: %v is not exist"

2024-10-25 02:26 UTC, littleniannian commented on sqle/server/auditplan/task_type_mysql_schema_meta.go
> +		return nil, fmt.Errorf("instance: %v is not exist", ap.InstanceID)
OK

2024-10-25 03:00 UTC, littleniannian commented on sqle/server/auditplan/task_type_mysql_schema_meta.go
> +		return nil, fmt.Errorf("instance: %v is not exist", ap.InstanceID)
这里更改为使用已经定义的`errors.NewInstanceNoExistErr()`

2024-10-25 06:59 UTC, ColdWaterLW approved these changes

2024-10-25 06:59 UTC, merged