feat: get backup strategy in audit result
actiontech/sqle pull request #2760
Opened 2024-11-15 03:23 UTC by winfredLIN

assign in @ColdWaterLW 
## 关联的 issue
https://github.com/actiontech/sqle-ee/issues/1956
测试 https://github.com/actiontech/sqle-ee/issues/1956#issuecomment-2477842021
按序提交，需要在以下PR合并后，再复审。有一部分commit在下面的PR中。
https://github.com/actiontech/sqle/pull/2756
https://github.com/actiontech/sqle-ee/pull/1978
## 描述你的变更
1. 支持工单在开启备份后，在SQL执行之前备份
## 确认项（pr提交后操作）
> [!TIP]
> 请在指定**复审人**之前，确认并完成以下事项，完成后✅
----------------------------------------------------------------------
- [X] 我已完成自测
- [X] 我已在关联的issue里补充了实现方案
- [X] 我已在关联的issue里补充了测试影响面
- [X] 我已确认了变更的兼容性，如果不兼容则在issue里标记 `not_compatible`
- [X] 我已确认了是否要更新文档，如果要更新则在issue里标记 `need_update_doc`
----------------------------------------------------------------------

2024-11-18 10:32 UTC, ColdWaterLW requested changes

2024-11-18 10:32 UTC, ColdWaterLW commented on sqle/server/sqled.go
> +			if err == nil {
err != nil没有处理

2024-11-18 10:32 UTC, ColdWaterLW commented on sqle/server/sqled.go
> +			affectedRows, err := a.plugin.EstimateSQLAffectRows(context.TODO(), sql.Content)
EstimateSQLAffectRows性能影响极大，需要减少影响范围

2024-11-20 11:19 UTC, ColdWaterLW requested changes

2024-11-21 02:14 UTC, winfredLIN commented on sqle/model/task.go
> +	IFNULL(backup_tasks.backup_strategy, '') AS backup_strategy,
OK

2024-11-22 02:30 UTC, closed without merging