feat: 规则分类重构
actiontech/sqle pull request #2835
Opened 2024-12-24 01:55 UTC by littleniannian

## 关联的 issue
https://github.com/actiontech/sqle/issues/2759
## 描述你的变更

## 确认项（pr提交后操作）
> [!TIP]
> 请在指定**复审人**之前，确认并完成以下事项，完成后✅
----------------------------------------------------------------------
- [x] 我已完成自测
- [x] 我已记录完整日志方便进行诊断
- [x] 我已在关联的issue里补充了实现方案
- [x] 我已在关联的issue里补充了测试影响面
- [x] 我已确认了变更的兼容性，如果不兼容则在issue里标记 `not_compatible`
- [x] 我已确认了是否要更新文档，如果要更新则在issue里标记 `need_update_doc`
----------------------------------------------------------------------

2024-12-24 02:23 UTC, littleniannian commented on sqle/api/app.go
> +		v1Router.GET("/rules/categoryStatistics", v1.GetCategoryStatistics)
获取分类信息统计接口

2024-12-24 02:23 UTC, littleniannian commented on sqle/api/controller/v1/rule.go
> +func associateCategories(categories []*model.AuditRuleCategory) map[string][]string {
该方法用于将tag在category维度进行聚合

2024-12-24 02:23 UTC, littleniannian commented on sqle/api/controller/v1/rule.go
> +func associateBizCategories(lang language.Tag, categories []*model.AuditRuleCategory) map[string][]string {
将tag转义为业务词汇，并且根据cateogory进行聚合

2024-12-24 02:23 UTC, littleniannian commented on sqle/api/controller/v1/rule.go
> +func parseRuleCategory(csvRule []string) map[string][]string {
csv文件的4，5，6，7列分别为四个维度的分类信息，获取这些并且进行转义

2024-12-24 02:23 UTC, littleniannian commented on sqle/api/controller/v1/rule.go
> +func ruleTemplateExportToParseDataV1(ruleTemplateExport *RuleTemplateExport, parseResData *ParseProjectRuleTemplateFileResDataV1) error {
该方法是为了处理之前解析json报错的问题，以为导出的json是以RuleTemplateExport的结构，这里反序列化后再转为ParseProjectRuleTemplateFileResDataV1

2024-12-24 02:23 UTC, littleniannian commented on sqle/api/controller/v1/rule.go
> +	Categories map[string][]string `json:"categories"`
自定义规则增加新分类字段

2024-12-24 02:23 UTC, littleniannian commented on sqle/api/controller/v1/rule.go
> +	Tags       *[]string `json:"tags" form:"tags"`
创建自定义接口，增加分类字段

2024-12-24 02:23 UTC, littleniannian commented on sqle/api/controller/v1/rule.go
> +	Tags       *[]string `json:"tags" form:"tags"`
修改自定义接口，增加分类字段

2024-12-24 02:23 UTC, littleniannian commented on sqle/driver/mysql/rule/rule_i18n_converter.go
> +func ConvertSourceRule(sr *SourceRule, allowOffline bool) *driverV2.Rule {
因为这里新的规则分类需要区分在线/离线，这里增加参数

2024-12-24 02:23 UTC, littleniannian commented on sqle/model/rule.go
> +func filterRulesByTag(ruleTemplateRules []RuleTemplateRule, tags string) []RuleTemplateRule {
根据tags,对rules进行过滤。

2024-12-24 02:23 UTC, littleniannian commented on sqle/model/rule.go
> +func templateRuleByTagsCondition(ruleCategories []*AuditRuleCategory, tags string) bool {
目前前端传来的tags都是来自不同category，不同的tag是&的关系

2024-12-24 02:23 UTC, littleniannian commented on sqle/model/utils.go
> +func (s *Storage) CreateRuleCategoriesRelated() error {
初始化分类表和自定义规则的分类关系

2024-12-24 02:23 UTC, littleniannian commented on sqle/model/utils.go
> +			categoryError := s.UpdateRuleCategoryRels(rule)
初始化规则的分类关系

2024-12-24 02:30 UTC, littleniannian commented on sqle/api/controller/v1/rule.go
> +func ruleTemplateExportToParseDataV1(ruleTemplateExport *RuleTemplateExport, parseResData *ParseProjectRuleTemplateFileResDataV1) error {
issue: https://github.com/actiontech/sqle-ee/issues/2112

2024-12-25 02:18 UTC, BugsGuru requested changes

2024-12-25 03:06 UTC, littleniannian commented on sqle/model/audit_rule_category.go
> +	return auditRuleCategory, nil
OK

2024-12-25 03:06 UTC, littleniannian commented on sqle/model/rule.go
> +				tagMatchCount++
OK

2024-12-25 03:19 UTC, littleniannian commented on sqle/driver/mysql/rule/rule_i18n_converter.go
> +		Category:     sr.Category.ID,
新的分类是为了替换旧的分类，我看到旧的分类之前也是做了国际化的。这块为了之后有国际化的可能，先把它做了

2024-12-25 03:25 UTC, littleniannian commented on sqle/driver/mysql/plocale/message_zh.go
OK

2024-12-25 05:43 UTC, littleniannian commented on sqle/api/app.go
> +		v1Router.GET("/rules/categoryStatistics", v1.GetCategoryStatistics)
目前的需求不需要

2024-12-25 07:07 UTC, littleniannian commented on sqle/driver/v2/driver_grpc_server.go
> +	AllowOffline bool
OK

2024-12-25 08:09 UTC, BugsGuru approved these changes

2024-12-25 08:10 UTC, merged